services:
  - type: web
    name: camshopping
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn camshopping.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: camshopping.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: your-django-secret-key
      - key: DEBUG
        value: False
